drop function if exists public.api_rate_buckets_prune();
drop function if exists public.vault_advance_branch(uuid, uuid, text, text, text);
drop function if exists public.api_record_call(uuid, uuid, text, text, int, int, bigint, bigint, text, text, text, jsonb);
drop function if exists public.api_key_authenticate(text);
drop function if exists public.api_keys_list(uuid);
drop function if exists public.api_key_revoke(uuid);
drop function if exists public.api_key_create(uuid, text, text[], int, timestamptz);
drop function if exists public.my_orgs();
drop function if exists public.org_create(text, text);
drop function if exists public.provenance_chain_verify(uuid);
drop function if exists public.provenance_chain_verify_service(uuid);
drop function if exists public.provenance_chain_append(uuid, uuid, text, jsonb);
drop table if exists public.vault_branches;
drop table if exists public.vault_commits;
drop table if exists public.vault_blobs;
drop table if exists public.vault_repos;
drop table if exists public.provenance_chain;
drop table if exists public.provenance_issuances;
drop table if exists public.provenance_assets;
drop table if exists public.api_usage_daily;
drop table if exists public.api_audit_log;
drop table if exists public.api_rate_buckets;
drop table if exists public.api_keys;
drop function if exists public.is_org_admin(uuid, uuid);
drop function if exists public.is_org_member(uuid, uuid);
drop table if exists public.org_members;
drop table if exists public.orgs;
delete from storage.buckets where id in ('provenance-originals', 'vault-blobs');
